name: Deploy

on:
  push:
    branches:
      - master # or the branch you want to deploy from


jobs:
  deploy:
    runs-on: ubuntu-latest #choose a github ubuntu machine

    steps:
    - name: Checkout code #clone the code to github machine
      uses: actions/checkout@v2 #This is opensource action that brings code to ubuntu machine

    - name: Prepare SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 600 keyfile
          ssh-keyscan ec2-13-211-144-149.ap-southeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts
          
    - name: SSH and deploy #redeploy 
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -t -i keyfile ubuntu@ec2-13-211-144-149.ap-southeast-2.compute.amazonaws.com "sudo bash ~/deploy.sh"

